import type { Metadata } from "next";
import {Header} from "@/components/Navigation";

export const metadata: Metadata = {
  title: "The Wedding Party",
  description: "Generated by create next app",
};

export default function TheBoys({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header transparent={false} />
      {children}
    </div>
  );
}
