import type { Metadata } from "next";
import Header from "../components/Navigation/Header2";
import { Pinyon_Script, Playfair_Display } from "next/font/google";
import "./globals.scss";

const Fancy = Pinyon_Script({
  weight: "400",
  variable: "--fancy",
  preload: false,
});

const Body = Playfair_Display({
  weight: ["400", "500", "600", "700"],
  variable: "--body",
  preload: false,
});

export const metadata: Metadata = {
  title: "Save the Date | Rachel & Anthony",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Fancy.variable} ${Body.variable} antialiased`}>
        <div className="pt-100 relative">{children}</div>
      </body>
    </html>
  );
}
