import type { Metadata } from "next";
import Header from "../../components/Navigation/Header";

export const metadata: Metadata = {
  title: "Gallery",
  description: "Generated by create next app",
};

export default function GalleryLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {" "}
      <Header />
      {children}
    </div>
  );
}
